.github/codecov.yml, .github/workflows/checks.yml
=> chore: collect test coverage

tests/__utils__/spawnTyche.ts
=> chore: tweak 'spawnTyche()' script

.github/codecov.yml
Configuring Codecov for non-blocking status checks.
=> chore: tweak Codecov config

src/store/ManifestWorker.ts
Since Node.js 18 it is possible to use Fetch API.
=> feat(store): use Node.js Fetch API

src/store/ManifestWorker.ts
=> Revert "feat(store): use Node.js Fetch API"

.github/workflows/checks.yml, package.json, src/collect/IdentifierLookup.ts, src/store/ManifestWorker.ts
=> Revert "chore: drop support for Node.js 16"

.github/workflows/checks.yml, .yarnrc.yml, package.json, yarn.lock
Downgrading Yarn to support lower Node.js versions.
=> chore(deps): downgrade Yarn

src/cli/Cli.ts
For better performance, `--help`, `--version` and similar command line options can be handled before full validation.
=> refactor(cli): defer validation of command line options

tests/command-line-options.test.ts
Adding a test for the `--prune` command line option.
=> chore: add test for the `--prune` command line option

src/store/StoreService.ts
Since #66 the same compiler instance is used to read TSTyche config and is passed to matchers later. Would be good to keep it cached instead of compiling twice. Performance is visible with naked eye. Yes!
Also something like `tstyche --target 5.3` would pick up the same cached instance without downloading it to store.
=> feat(store): cache compiled compiler instances

.github/workflows/benchmarks.yml, benchmarks/tsconfig.json, benchmarks/tstyche.bench.js, c8.config.json, cspell.config.json, eslint.config.json, package.json, yarn.lock
Sounds useful to have some minimal benchmarks.
=> chore: add minimal benchmarks

.github/workflows/benchmarks.yml, benchmarks/examples.bench.sh
Forgot to drop `npm` cache as well.
=> chore(bench): clean `npm` cache before each timing run

src/store/StoreService.ts
Fixes #82
This is a quick fix for `target: current` support for TypeScript 5.2 and below. Tested locally and it works. Fine to be released for now. As the next step I must setup testing infrastructure for different TS versions to avoid similar issues.
=> fix(store): fix `"target": ["current"]` support for TypeScript 5.2 and below

src/cli/Cli.ts, src/store/ManifestWorker.ts, tests/command-line-options.test.ts, tests/config-update.test.ts, tests/validation-update.test.ts
Adds validation test for the `--update` command line option.
=> refactor(cli, store): clean up code related with the `--update` option

.github/workflows/checks.yml
Part of #136
Building on Node.js LTS and reusing the built files would be fun.
=> chore(ci): reuse built files

source/cli/Cli.ts, source/config/CommandLineOptionsWorker.ts, source/config/OptionDiagnosticText.ts, source/config/OptionValidator.ts, source/environment/Environment.ts, tests/validation-watch.test.js
The watch mode cannot be enabled in a continuous integration environment.
=> fix(cli, config, environment): do not allow `--watch` in CI environment

source/api/TSTyche.ts, source/file/TestFile.ts, source/file/index.ts, source/output/__tests__/fileStatusText.test.js, source/output/fileStatusText.tsx, source/result/FileResult.ts, source/result/Result.ts, source/result/TargetResult.ts, source/runner/TaskRunner.ts, source/runner/TestFileRunner.ts, source/runner/TestTreeWorker.ts, source/tstyche.ts, tests/__fixtures__/feature-programmatic-api/__typetests__/toBeNumber.tst.ts, tests/__fixtures__/feature-programmatic-api/__typetests__/toBeString.tst.ts, tests/__fixtures__/feature-programmatic-api/tsconfig.json, tests/feature-programmatic-api.test.js
This PR adds the `TestFile` class, which replaces `URL` and consolidates normalisation logic.
=> feat(file): add the `TestFile` class

source/cli/Cli.ts, source/events/EventEmitter.ts
Replacing `EventEmitter`s method `removeHandler()` with `removeAllHandlers()`.
=> refactor(events)!: replace `removeHandler()` with `removeAllHandlers()` method

source/config/OptionDiagnosticText.ts, source/config/OptionValidator.ts, source/watch/WatchService.ts, tests/feature-watch-mode.test.js, tests/validation-watch.test.js
Adding a check if recursive watch is available on the system.
=> feat(config, watch): check if recursive watch is available

.editorconfig, mocha.config.json, package.json
Only watch mode test cannot be run in parallel. Other should work.
=> chore: run tests in parallel

source/api/TSTyche.ts, source/cli/Cli.ts
It must be always allowed passing `cancellationToken` as an argument.
=> refactor(api, cli): always allow passing `cancellationToken` as an argument

source/collect/TestMember.ts, source/config/ConfigFileOptionsWorker.ts, source/diagnostic/Diagnostic.ts, source/diagnostic/DiagnosticOrigin.ts, source/diagnostic/index.ts, source/expect/Expect.ts, source/runner/TestTreeWorker.ts
This is simply an attempt to reduce duplication in older code parts.
=> feat(diagnostic): add the `DiagnosticOrigin` class

source/input/InputService.ts, source/watch/WatchService.ts
Would be better to receive string chunks from `stdin`.
=> fix(input): normalize input chunk

.github/workflows/checks.yml, package.json, tests/config-storePath.test.js
Just for fun, let’s try to collect platform specific coverage.
=> chore: collect platform specific coverage

.github/workflows/checks.yml
As it was suggested in https://github.com/cenfun/monocart-coverage-reports/pull/49#issuecomment-2198592145
=> chore(ci): fix generate coverage script

source/expect/Expect.ts, source/expect/ToHaveProperty.ts, source/runner/TestTreeWorker.ts, tests/__snapshots__/api-toHaveProperty-stderr.snap.txt
After #238 messages of `.toHaveProperty()` can be improved:
=> feat(expect): improve `.toHaveProperty()` messages

package.json, source/cli/Cli.ts, source/environment/Environment.ts, source/store/ManifestWorker.ts, source/store/PackageInstaller.ts, source/store/StoreService.ts, tests/config-npmRegistry.test.js, yarn.lock
Adding the `TSTYCHE_NPM_REGISTRY` environment variable to make it possible to use a custom registry.
=> feat: add the `TSTYCHE_NPM_REGISTRY` environment variable

source/store/Fetcher.ts, source/store/ManifestWorker.ts, source/store/StoreService.ts, tests/validation-update.test.js
Moving all fetch logic to separate `Fetcher` class. So it can be reused in #269.
=> feat(store): add the `Fetcher` class

.github/workflows/checks.yml, package.json, source/environment/Environment.ts, source/store/ManifestWorker.ts, source/tsconfig.json, tests/config-install.test.js, tests/config-npmRegistry.test.js, tests/config-prune.test.js, tests/config-storePath.test.js, tests/config-target.test.js, tests/config-typescriptPath.test.js, tests/config-update.test.js, tests/feature-store.test.js, tests/feature-typescript-versions.test.js, tests/validation-store.test.js, tests/validation-target.test.js, tests/validation-update.test.js, tsconfig.json
Closes #267
Dropping support for Node.js 16.
=> chore!: drop support for Node.js 16

source/cli/Cli.ts, source/store/ManifestService.ts, source/store/StoreService.ts
For better semantics, adding `prune()` method to `StoreService` class.
=> feat(cli, store): add `prune()` method to `StoreService` class

package.json, yarn.lock
=> Revert "chore(deps): update dependency monocart-coverage-reports to v2.10.7"

source/api/TSTyche.ts, source/handlers/ListReporter.ts, source/handlers/index.ts
Renaming the `ListReporter` class.
=> refactor!: rename the `ListReporter` class

source/collect/Collect.ts, source/collect/index.ts, source/runner/TaskRunner.ts
=> refactor!: rename the `Collect` class

source/result/TargetResult.ts, source/runner/Runner.ts, tests/feature-typescript-versions.test.js
=> refactor(result)!: rename `target` property

.github/workflows/checks.yml
=> chore: test on Node.js 23

.github/workflows/checks.yml, package.json, source/config/Options.ts, source/environment/Environment.ts, source/store/Store.ts, tests/config-typescriptPath.test.js, tests/feature-typescript-versions.test.js
I think it is time to use `import.meta.resolve()`.
=> refactor!: use `import.meta.resolve()`

source/plugins/index.ts, source/plugins/types.ts
Exposing the `SelectHookContext` type.
=> feat: expose the `SelectHookContext` type

.gitignore, DEVELOPMENT.md
Just some notes from getting my local environment set up better.  The `.gitignore` entries are for JB/IJ/WS IDE project files.
=> feat: Development markdown and ignore JetBrains IDE files

source/runner/Runner.ts, source/watch/WatchService.ts, tests/__snapshots__/feature-watch-config-file-has-an-error-stdout.snap.txt, tests/__snapshots__/feature-watch-config-file-is-added-stdout.snap.txt, tests/__snapshots__/feature-watch-config-file-is-changed-stdout.snap.txt, tests/__snapshots__/feature-watch-config-file-is-removed-stdout.snap.txt, tests/__snapshots__/feature-watch-config-option-stdout.snap.txt, tests/__snapshots__/feature-watch-exit-stdout.snap.txt, tests/__snapshots__/feature-watch-failFast-option-stdout.snap.txt, tests/__snapshots__/feature-watch-multiple-test-files-are-added-stdout.snap.txt, tests/__snapshots__/feature-watch-multiple-test-files-are-changed-stdout.snap.txt, tests/__snapshots__/feature-watch-multiple-test-files-are-removed-stdout.snap.txt, tests/__snapshots__/feature-watch-multiple-test-files-are-renamed-stdout.snap.txt, tests/__snapshots__/feature-watch-no-test-files-left-stdout.snap.txt, tests/__snapshots__/feature-watch-no-test-files-selected-stdout.snap.txt, tests/__snapshots__/feature-watch-run-all-stdout.snap.txt, tests/__snapshots__/feature-watch-single-test-file-is-added-stdout.snap.txt, tests/__snapshots__/feature-watch-single-test-file-is-changed-stdout.snap.txt, tests/__snapshots__/feature-watch-single-test-file-is-removed-stdout.snap.txt, tests/__snapshots__/feature-watch-single-test-file-is-renamed-stdout.snap.txt, tests/__utilities__/process.js, tests/feature-watch.test.js
Non-interactive environments must be respected in watch mode. It should not expect any input and should not clear output as well.
=> feat: respect non-interactive environments in watch mode

biome.json, source/collect/CollectService.ts, source/collect/TestMember.ts, source/collect/TestTree.ts, source/events/types.ts, source/handlers/TestTreeHandler.ts, source/handlers/index.ts, source/runner/Runner.ts
Closes #410
Adding `collect:start`, `collect:node` and `collect:end` events.
=> feat: add `collect:*` events

source/config/Target.ts, source/store/Manifest.ts, source/store/ManifestService.ts, tests/config-prune.test.js, tests/config-update.test.js, tests/feature-store.test.js, tests/validation-store.test.js, tests/validation-update.test.js
Adding the `minotVersions` property to store manifest.
=> feat!: add the `minotVersions` property to store manifest

.github/workflows/benchmarks.yml, .github/workflows/checks.yml, .github/workflows/nightly.yml
=> chore: add workflow permissions

source/glob/Braces.ts, source/glob/Glob.ts, source/glob/index.ts, source/select/Select.ts, source/tstyche.ts, tests/__snapshots__/config-testFileMatch-braces-span-several-segments-stdout.snap.txt, tests/config-testFileMatch.test.js
Expanding braces early allows to cover more use cases.
=> refactor(glob): expand braces early

source/store/PackageService.ts, source/store/TarReader.ts
This should be somewhat more memory efficient.
Also one of Node.js APIs is removed. A small step towards #508.
=> refactor(store): read tarball content from the stream

scripts/generate-types.js, source/config/CommandLineParser.ts, source/config/OptionBrand.enum.ts, source/config/Options.ts, source/output/__tests__/helpText.test.js, source/output/helpText.tsx
=> refactor!: rename `OptionBrand.True`
