tstyche/tstyche

tests/__snapshots__/command-line-options.test.ts.snap, tests/command-line-options.test.ts
Adding a test for the '--target' command line option.
=> chore: add e2e test for the '--target' option

tests/__utils__/spawnTyche.ts
What happens on Windows if a process gets spawned with 'windowsVerbatimArguments: true'?
=> chore: try spawning a process with 'windowsVerbatimArguments: true'

src/store/CompilerModuleWorker.ts, tests/__utils__/spawnTyche.ts, tests/command-line-options.test.ts
Adding end-to-end test for the `--target` command line option.
=> fix(store): normalize `installationPath` path output

src/checker/Checker.ts, src/types.ts, tests/__snapshots__/api-expect.test.ts.snap, tests/__snapshots__/api-toBeAny.test.ts.snap, tests/__snapshots__/api-toBeBigInt.test.ts.snap, tests/__snapshots__/api-toBeBoolean.test.ts.snap, tests/__snapshots__/api-toBeNever.test.ts.snap, tests/__snapshots__/api-toBeNull.test.ts.snap, tests/__snapshots__/api-toBeNumber.test.ts.snap, tests/__snapshots__/api-toBeString.test.ts.snap, tests/__snapshots__/api-toBeSymbol.test.ts.snap, tests/__snapshots__/api-toBeUndefined.test.ts.snap, tests/__snapshots__/api-toBeUniqueSymbol.test.ts.snap, tests/__snapshots__/api-toBeUnknown.test.ts.snap, tests/__snapshots__/api-toBeVoid.test.ts.snap
The behaviour of primitive type matchers and the `.toEqual()` matcher is the same. Their error messages should be the same too.
=> fix(checker): clean up error messages of primitive type matchers

.github/workflows/checks.yml, package.json, src/collect/IdentifierLookup.ts, src/store/ManifestWorker.ts
Dropping support for Node.js 16, because it is an End-of-Life version already.
=> chore: drop support for Node.js 16

src/runner/TestTreeWorker.ts, tests/__fixtures__/api-describe/__typetests__/describe-only.test.ts, tests/__fixtures__/api-describe/__typetests__/describe-skip.test.ts, tests/__fixtures__/api-describe/__typetests__/describe-todo.test.ts, tests/__fixtures__/api-expect/__typetests__/expect-only-fail.test.ts, tests/__fixtures__/api-expect/__typetests__/expect-only.test.ts, tests/__fixtures__/api-expect/__typetests__/expect-skip.test.ts, tests/__fixtures__/api-it/__typetests__/it-only.test.ts, tests/__fixtures__/api-it/__typetests__/it-skip.test.ts, tests/__fixtures__/api-it/__typetests__/it-todo.test.ts, tests/__fixtures__/api-test/__typetests__/test-only.test.ts, tests/__fixtures__/api-test/__typetests__/test-skip.test.ts, tests/__fixtures__/api-test/__typetests__/test-todo.test.ts, tests/__snapshots__/api-describe.test.ts.snap, tests/__snapshots__/api-expect.test.ts.snap, tests/__snapshots__/api-file.test.ts.snap, tests/__snapshots__/api-imports.test.ts.snap, tests/__snapshots__/api-it.test.ts.snap, tests/__snapshots__/api-test.test.ts.snap
Noticed some difference between explicit `.skip` and implicit skip caused by `.only`.
=> fix(runner): tune up behavior of run mode flags

.github/workflows/checks.yml, .github/workflows/nightly.yml
Let's run daily smoke test on TypeScript's nightly builds.
=> chore: setup smoke test on TypeScript's nightly builds

src/store/CompilerModuleWorker.ts, src/store/Lock.ts, src/store/StoreService.ts
Moving retry logic to the `Lock` class:
- this allows using `onDiagnostic()` instead of throwing an error;
- and does not need `node:timers/promises` anymore.
=> refactor: move retry logic to the `Lock` class

lib/__tests__/__fixtures__/valid-target.json, lib/__tests__/__snapshots__/schema.test.ts.snap, lib/schema.json, src/config/OptionDefinitionsMap.ts, src/config/OptionUsageText.ts, src/store/StoreService.ts, tests/__snapshots__/command-line-options.test.ts.snap, tests/__snapshots__/config-file-options.test.ts.snap, tests/command-line-options.test.ts, tests/config-file-options.test.ts
Two users asked for a possibility to run type test on the same version of TypeScript as the one currently installed in the repo. Having an option makes it easy to keep both versions in sync. Nice idea.
This PR is adding the `current` target tag, which makes this possible:
bash
```
tstyche --target current
```
Or via config file:
```json
{
"target": ["4.9", "current"]
}
```
---
`latest` stays as the default. This is because TSTyche can be used without installing TypeScript. Using `current` as a default cannot work in repos with `typescript` installed. Would be possible to use `latest` as a fallback, but I am not sure if it is good idea to change the default just because a package is getting installed or uninstalled.
=> feat: add support for the `current` target tag

src/checker/Checker.ts, tests/__fixtures__/api-toRaiseError/__typetests__/toRaiseError.test.ts, tests/__snapshots__/api-toRaiseError.test.ts.snap
Closes #34
I was in a hurry and forgot to check some details with previous patch. It did not work still. Now everything is double checked and tested.
=> fix: use `.isStringLiteralLike()` to take template literals as arguments

tests/__fixtures__/api-toRaiseError/__typetests__/toRaiseError.test.ts, tests/__snapshots__/api-toRaiseError.test.ts.snap
The `.toRaiseError()` matcher is missing few test cases. Adding those.
=> chore: add missing tests for the `.toRaiseError()` matcher

tests/__snapshots__/command-line-options.test.ts.snap, tests/command-line-options.test.ts
The `--skip` command line option had no tests. Time to add these too.
=> chore: add tests for the `--skip` command line option

tests/command-line-options.test.ts
Adding a test for the `--version` command line option.
=> chore: add test for the `--version` command line option

src/project/ProjectService.ts
Resolves #55
This change makes sure that language service plugins specified in `tsconfig.json` will be loaded for type testing.
For example, to make TypeScript recognize imports of `.vue` files, a user has to install the `typescript-vue-plugin` package and add it to the [`plugins`](https://typescriptlang.org/tsconfig#plugins) list of the `tsconfig.json` nearest to type test files:
```json
{
"compilerOptions": {
"plugins": [{ "name": "typescript-vue-plugin" }]
}
}
```
=> feat: load local language service plugins

scripts/generate-types.js, src/config/CommandLineOptionsWorker.ts, src/config/OptionBrand.ts, src/config/OptionDefinitionsMap.ts, src/config/OptionGroup.ts
Command line options that do not take any value, must always be `true` and ignore any provided value.
=> fix(config): correctly handle command line options that do not take a value

src/collect/Assertion.ts, src/collect/CollectService.ts, src/collect/TestMember.ts, src/collect/TestTree.ts, src/expect/Expect.ts, src/runner/TestFileRunner.ts, src/runner/TestTreeWorker.ts
Using `Set`s to handle TypeScript diagnostics, simplifies logic (and might improve performance as well).
=> refactor(collect, expect, runner): use `Set` to handle TypeScript diagnostic

eslint.config.json, src/store/CompilerModuleWorker.ts, src/store/StoreService.ts, src/store/Version.ts, src/store/__tests__/Version.test.ts
Since TypeScript 5.3 it is recommended to load `typescript.js` instead of `tsserverlibrary.js`. This change makes the TypeScript module loading a bit more version aware.
Reference: https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes#typescript-53
=> fest(store): make the TypeScript module loading more version aware

src/store/StoreService.ts
Let’s use dynamic `import()` to load the TypeScript module.
=> refactor(store): use dynamic `import()` to load the TypeScript module

rollup.config.js, src/api/TSTyche.ts
Let’s use Rollup to inject the version string during the build step. Less code to ship.
=> refactor(api): inject the version string during the build step

src/store/ManifestWorker.ts, tests/validation-store-manifest.test.ts, tests/validation-store.test.ts
Keeping store versioned allows newer versions of TSTyche to purge cache if it was created by older version. After #64 it is good idea to recreate files kept in the store.
=> feat(store): add `$version` field to store manifest

src/cli/Cli.ts, src/store/ManifestWorker.ts, src/store/StoreService.ts, tests/command-line-options.test.ts
The `--update` command line option can simply initialize the `Store` and require to refresh the manifest.
=> refactor(cli, store): improve logic of the `--update` command line option

.github/workflows/checks.yml, c8.config.json, cspell.config.json
Right now the result of `text` reporter is more correct than `lcov`. Switching to `json` to have correct data on Codecov.
=> chore: use `json` coverage reporter

tests/feature-typescript-versions.test.ts
Adding a smoke test for all supported major versions of TypeScript.
This is the missing test for #83
=> chore: add a smoke test for all supported major versions of TypeScript

examples/tsconfig.json, package.json, rollup.config.js, scripts/tsconfig.json, src/api/TSTyche.ts, src/bin.ts, src/cli/Cli.ts, src/environment/Environment.ts, src/logger/Logger.ts, src/store/Lock.ts, tests/__fixtures__/tsconfig.json, tests/tsconfig.json, tsconfig.json, typetests/tsconfig.json, yarn.lock
Importing Node.js types explicitly instead of relying on `types: ["node"]` magic. Somehow feels cleaner. At least this makes the output files cleaner.
=> refactor: import Node.js types explicitly

lib/CommandLineOptions.ts, lib/ConfigFileOptions.ts, lib/__tests__/__fixtures__/invalid-disableTestFileLookup.json, lib/__tests__/__fixtures__/valid-all-options.json, lib/__tests__/__fixtures__/valid-disableTestFileLookup.json, lib/__tests__/__snapshots__/schema.test.js.snap, lib/__tests__/schema.test.js, lib/schema.json, src/cli/Cli.ts, src/config/ConfigService.ts, src/config/OptionDefinitionsMap.ts, tests/__snapshots__/config-disableTestFileLookup.test.js.snap, tests/__snapshots__/config-file-options.test.js.snap, tests/__snapshots__/config-help.test.js.snap, tests/__snapshots__/config-listFiles.test.js.snap, tests/__snapshots__/validation-runner.test.js.snap, tests/config-disableTestFileLookup.test.js, tests/config-file-options.test.js, tests/config-listFiles.test.js, tests/validation-runner.test.js, typetests/CommandLineOptions.tst.ts, typetests/ConfigFileOptions.tst.ts
Replace the `allowNoTestFiles` option with `disableTestFileLookup`. It does almost the same, but will work better with programmatic API (coming soon!).
=> refactor: replace the `allowNoTestFiles` option with `disableTestFileLookup`

source/config/ConfigService.ts, tests/__snapshots__/feature-runner.test.js.snap, tests/feature-runner.test.js, tstyche.config.json
Adding a list of file extensions. Currently `.json` or `.snap` files get selected, but this does not make sense. This change makes it easier to write `testFileMatch` patterns as well.
=> feat(config): only select test files with supported extensions

source/diagnostic/Diagnostic.ts, source/scribbler/Line.tsx, source/scribbler/Scribbler.ts, source/scribbler/__tests__/Line.test.tsx, tests/config-storePath.test.js, tests/feature-store.test.js, tests/feature-typescript-versions.test.js, tests/validation-store.test.js, tests/validation-target.test.js
Makes the end of line sequence configurable and use `\n` as default. 
Currently `\r\n` is used to make VS Code's Testing API happy. I can use the option there.
=> refactor(diagnostic, scribbler): make the end of line sequence configurable

source/project/ProjectService.ts, tests/feature-typescript-versions.test.js
Closes #109
Setting `module: "preserve"` in the default compiler options for inferred project that are using TypeScript 5.4 and up.
Reference: https://devblogs.microsoft.com/typescript/announcing-typescript-5-4-beta/#support-for-require-calls-in-moduleresolution-bundler-and-module-preserve
=> feat(project): set `module: "preserve"` in the default compiler options

source/cli/Cli.ts, tests/__snapshots__/config-testFileMatch.test.js.snap, tests/config-listFiles.test.js, tests/config-testFileMatch.test.js
When the `testFileMatch` option is specified as an empty list, no test files should be selected. This is similar how the `target` option works.
=> fix(cli): do not select files, if `testFileMatch` is an empty list

examples/Options.tst.ts, source/expect/Expect.ts, source/expect/ToMatch.ts, source/expect/types.ts, source/store/StoreService.ts, tests/__fixtures__/api-toMatch/__typetests__/toMatch.tst.ts, tests/__snapshots__/api-toMatch.test.js.snap, tests/feature-typescript-versions.test.js
Use strict subtyping check when possible (since TS 5.x). For example, the following example only passes with `readonly` modifier:
```ts
import { expect, test } from "tstyche";
interface Options {
readonly environment?: string;
timers?: "fake" | "real";
}
const options: Options = {};
test("is a match?", () => {
expect(options).type.toMatch<{ readonly environment?: string }>();
expect(options).type.toMatch<{ timers?: "fake" | "real" }>();
});
```
=> fix(expect, store): use strict subtyping check

.github/workflows/checks.yml, benchmarks/tstyche.bench.sh, source/expect/Expect.ts, source/expect/ToBeAssignable.ts, source/expect/ToEqual.ts, source/expect/ToMatch.ts, source/expect/types.ts, source/runner/TestFileRunner.ts, source/store/StoreService.ts
Refactoring to use the `isTypeRelatedTo()` method for type relationship checks. Only difference: this makes possible to have strict subtype relationship checks in TypeScript 4.x.
=> refactor(expect, runner, store): use the `isTypeRelatedTo()` method

source/config/OptionValidator.ts, source/store/StoreService.ts
If the store failed to open, the 'Supported tags..." message should be omitted. Currently it creates unnecessary noise.
=> fix(config, store): do not validated tags if the store failed to open

source/output/CodeSpanText.tsx, source/path/Path.ts, source/scribbler/Scribbler.ts, tests/__utils__/normalizeOutput.js
Part of #136
This PR replaces `String.prototype.replaceAll()` with `String.prototype.replace()`.
=> refactor: use `String.prototype.replace()`

source/types.ts
`.toBeAssignable()` has been renamed to `.toBeAssignableWith()` (see #141).
=> feat(types): deprecate `.toBeAssignable()` in favour of `.toBeAssignableWith()`

models/ConfigFileOptions.ts, models/__tests__/__fixtures__/invalid-fileExtensions-1.json, models/__tests__/__fixtures__/invalid-fileExtensions-3.json, models/__tests__/__fixtures__/invalid-fileExtensions-4.json, models/__tests__/__fixtures__/valid-all-options.json, models/__tests__/__fixtures__/valid-fileExtensions.json, models/__tests__/config-schema.test.js, models/__typetests__/ConfigFileOptions.tst.ts, models/config-schema.json, source/config/ConfigService.ts, source/config/OptionDefinitionsMap.ts, tests/__snapshots__/config-fileExtensions-default-list-stdout.snap.txt, tests/__snapshots__/config-fileExtensions-specified-extensions-stdout.snap.txt, tests/__snapshots__/validation-fileExtensions-wrong-list-item-type-stderr.snap.txt, tests/__snapshots__/validation-fileExtensions-wrong-option-value-type-stderr.snap.txt, tests/config-fileExtensions.test.js, tests/validation-fileExtensions.test.js
It makes sense to allow configuring `fileExtensions`, instead of predefined list. For instance, TSTyche could be used to type check `svelte` files.
=> feat(config, models): add the `fileExtensions` configuration option

README.md, examples/MethodLikeKeys.tst.ts, examples/firstItem.tst.ts, examples/function-types.tst.ts, source/collect/CollectService.ts, source/expect/Expect.ts, source/expect/ToBe.ts, source/types.ts, tests/__fixtures__/api-toBe/__typetests__/toBe.tst.ts, tests/__fixtures__/api-toBe/tsconfig.json, tests/__fixtures__/validation-toBe/__typetests__/toBe.tst.ts, tests/__fixtures__/validation-toBe/tsconfig.json, tests/__snapshots__/api-toBe-stderr.snap.txt, tests/__snapshots__/api-toBe-stdout.snap.txt, tests/__snapshots__/api-toBeAssignable-stderr.snap.txt, tests/__snapshots__/api-toEqual-stderr.snap.txt, tests/__snapshots__/validation-toBe-stderr.snap.txt, tests/__snapshots__/validation-toBe-stdout.snap.txt, tests/__snapshots__/validation-toBeAssignable-stderr.snap.txt, tests/__snapshots__/validation-toEqual-stderr.snap.txt, tests/api-toBe.test.js, tests/feature-runner.test.js, tests/feature-typescript-versions.test.js, tests/validation-toBe.test.js
This is just a matcher rename from `.toEqual()` to `.toBe()`.
I think it was a mistake to call it `.toEqual()`. It would be fine to keep it, but I see why renaming makes sense.
First equality exists between values, but types are not values (they are models, shapes, but not values).
Second, it reads better and fits well with primitive type matchers:
```ts
.type.toBe<number | undefined>();
.type.toBeNumber();
.type.toBeUndefined();
```
This matcher checks identity that’s why it must be called `.toBe()`.
=> refactor!(collect, expect): rename `.toEqual()` to `.toBe()`

source/config/CommandLineOptionsWorker.ts, source/config/ConfigFileOptionsWorker.ts, source/config/OptionDiagnosticText.ts, source/config/OptionUsageText.ts, tests/__snapshots__/validation-configFile-tabs-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-configFile-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-failFast-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-rootPath-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-target-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-testFileMatch-wrong-option-value-type-stderr.snap.txt, tests/config-failFast.test.js, tests/validation-configFile.test.js, tests/validation-only.test.js, tests/validation-skip.test.js, tests/validation-target.test.js
Refactoring error messages to use 'option value' consistently.
=> refactor(config): use 'option value' consistently in error messages

eslint.config.json, source/events/EventEmitter.ts, source/expect/Expect.ts, source/reporters/ThoroughReporter.ts, source/result/ResultManager.ts, source/types.ts, tests/__snapshots__/api-toBeAssignable-stderr.snap.txt, tests/__snapshots__/api-toEqual-stderr.snap.txt, tests/__snapshots__/validation-toBeAssignable-stderr.snap.txt, tests/__snapshots__/validation-toEqual-stderr.snap.txt, tsconfig.json
Less noise. It is enough to warn only once per deprecation.
=> refactor: warn only once per deprecation

source/runner/TaskRunner.ts
No need to return the `Result`, it can be picked up from the `run:end` event.
=> refactor(runner)!: do not return the `Result`

source/api/TSTyche.ts, source/runner/TaskRunner.ts, tests/feature-programmatic-api.test.js
The `TaskRunner` has `resolvedConfig.target` option set already, let’s use it.
=> refactor(runner)!: use `resolvedConfig.target` option

.github/workflows/checks.yml, package.json, tests/__utilities__/process.js, tests/__utilities__/tstyche.js, tests/validation-store.test.js
Dropping support for Node.js 14.
=> chore: drop support for Node.js 14

cspell.config.json, source/output/CodeSpanText.tsx, source/output/addsPackageStepText.tsx, source/output/describeNameText.tsx, source/output/diagnosticText.tsx, source/output/fileStatusText.tsx, source/output/fileViewText.tsx, source/output/formattedText.tsx, source/output/helpText.tsx, source/output/summaryText.tsx, source/output/testNameText.tsx, source/output/usesCompilerStepText.tsx, source/output/watchModeUsageText.tsx, source/scribbler/Line.tsx, source/scribbler/Scribbler.ts, source/scribbler/Text.tsx, source/tsconfig.json
It is time to use the `jsx-runtime` transform instead of `Scribbler.createElement`.
=> refactor(output, scribbler)!: use the `jsx-runtime` transform

source/config/ConfigService.ts, tests/config-configFile.test.js, tests/config-rootPath.test.js
Always set `configFilePath` property in the resolved config. This can be useful to watch the config file for changes.
=> feat(config)!: always set `configFilePath` property in the resolved config

source/api/TSTyche.ts, source/cli/Cli.ts, source/events/EventEmitter.ts, source/runner/TaskRunner.ts, source/runner/WatchModeManager.ts, tests/feature-programmatic-api.test.js
Removing all event handlers breaks the logic. Hence adding and removing handlers should be done separately for each scope.
=> feat(api, cli, events, runner): add and remove event handlers for each scope

source/api/TSTyche.ts, source/cli/Cli.ts, source/cli/ExitCodeHandler.ts, source/events/EventEmitter.ts, source/reporters/ExitCodeReporter.ts, source/reporters/index.ts, tests/feature-watch.test.js
This change allows reporting the exit code of the last test rerun (in the watch mode). Also the exit code will be handled in a single place.
=> feat: report the exit code of the last test rerun

source/store/ManifestWorker.ts, source/store/StoreDiagnosticText.ts, tests/config-configFile.test.js, tests/config-install.test.js, tests/config-storePath.test.js, tests/config-target.test.js, tests/config-typescriptPath.test.js, tests/config-update.test.js, tests/feature-store.test.js, tests/feature-typescript-versions.test.js, tests/validation-store.test.js, tests/validation-target.test.js
It is time to use `fetch()` global (and to ship lees code).
This means that testing on specified versions of TypeScript will not be supported on Node.js 16. The rest works as expected, so I think that is fine.
=> refactor(store)!: use `fetch()` global

source/config/OptionDiagnosticText.ts, source/config/OptionValidator.ts, source/select/GlobPattern.ts, tests/__snapshots__/config-testFileMatch-specified-patterns-start-with-dot-stdout.snap.txt, tests/__snapshots__/validation-testFileMatch-cannot-start-with-0.snap.txt, tests/__snapshots__/validation-testFileMatch-cannot-start-with-1.snap.txt, tests/config-testFileMatch.test.js, tests/validation-testFileMatch.test.js
It must be allowed to have `./` in the beginning of `testFileMatch` patterns.
=> fix(config): allow `./` in the beginning of `testFileMatch` patterns

source/handlers/RuntimeReporter.ts
It sounds like a better idea to show deprecation warnings for each file. One can instantly see how many files must be updated. That’s essentially better in the watch mode.
=> fix(runner): show deprecation warnings for each test file

source/watch/WatchService.ts, tests/feature-watch.test.js
Reference: https://github.com/FloEdelmann/vue-ts-types/pull/574#issuecomment-2149820371
It sounds useful to add `q` as one more alias to exit the watch mode.
=> feat(watch): exit the watch mode when `q` or `Q` is pressed

source/output/CodeSpanText.tsx, source/output/diagnosticText.tsx, source/output/fileStatusText.tsx, source/output/formattedText.tsx, source/output/helpText.tsx, source/output/summaryText.tsx, source/output/testNameText.tsx, source/output/usesCompilerStepText.tsx, source/scribbler/Line.tsx, source/scribbler/Scribbler.ts, source/scribbler/Text.tsx, source/scribbler/index.ts, source/scribbler/jsx-runtime.ts, source/scribbler/types.ts
This was supposed to be part of #199. Class components aren’t very useful. Migrating to function components reduces code duplication and complexity.
=> refactor(output, scribbler): use function components

source/collect/CollectService.ts, source/expect/Expect.ts, tests/__fixtures__/validation-expect/__typetests__/matcher-not-supported.tst.ts, tests/__snapshots__/validation-expect-handles-nested-stdout.snap.txt, tests/__snapshots__/validation-expect-handles-not-supported-matcher-stderr.snap.txt, tests/__snapshots__/validation-expect-handles-not-supported-matcher-stdout.snap.txt, tests/validation-expect.test.js
The typings guard against using matching which are not implemented. In rear cases (e.g. `// @ts-expect-error`) that does not work.
Also nice to remove few lines of older code.
=> fix(expect): handle not supported matchers

source/watch/FileWatcher.ts, source/watch/Watcher.ts
There is no need to wrap around the async `fs.watch` and I don’t like semantics of caching an error which is not an error. Always possible to bring this back, if it would appear useful.
=> feat(watch): wrap around sync `fs.watch`

source/config/ConfigFileOptionsWorker.ts, tests/config-configFile.test.js
Split from #238.
Empty config file (eg. with all lines commented out) must be allowed.
=> fix(config): allow empty config file

source/diagnostic/Diagnostic.ts, tests/__snapshots__/validation-configFile-syntax-error.snap.txt, tests/__snapshots__/validation-type-errors-describe-level-errors-stderr.snap.txt
When provided by TypeScript, related diagnostics should be added to the error messages.
=> feat(diagnostic): show related diagnostics, when provided by TypeScript

source/expect/Expect.ts, source/expect/ExpectDiagnosticText.ts
Moving messages to `ExpectDiagnosticText` class.
=> refactor(expect): add the `ExpectDiagnosticText` class

source/expect/Expect.ts, source/expect/ExpectDiagnosticText.ts, source/expect/ToRaiseError.ts, source/expect/index.ts, source/expect/types.ts, source/runner/TestTreeWorker.ts, tests/__snapshots__/api-toRaiseError-stderr.snap.txt, tests/__snapshots__/validation-toRaiseError-stderr.snap.txt
The messages of `.toRaiseError()` now will mark the origin:
=> feat(expect): improve `.toRaiseError()` messages

source/diagnostic/Diagnostic.ts, source/expect/ToAcceptProps.ts
Adding `.extendWith()` method to `Diagnostic`. It updates the `origin`, adds more `text` and returns new `Diagnostic`.
=> feat(diagnostic, expect): add `.extendWith()` method to `Diagnostic`

source/collect/Assertion.ts, source/collect/TestMember.ts, source/output/CodeSpanText.tsx
Moving the `breadcrumbs` to an output component, because `ancestorNames` are only useful in the output.
=> refactor(collect, output): move the `breadcrumbs` logic to a component

biome.json, cspell.config.json, models/__tests__/config-schema.test.js, package.json, source/output/__tests__/describeNameText.test.js, source/output/__tests__/diagnosticText.test.js, source/output/__tests__/fileStatusText.test.js, source/output/__tests__/formattedText.test.js, source/output/__tests__/helpText.test.js, source/output/__tests__/testNameText.test.js, source/output/__tests__/usesCompilerStepText.test.js, source/version/__tests__/Version.test.js, yarn.lock
Let’s use `poku` to run unit tests.
=> chore: use `poku` to run unit tests

source/store/StoreService.ts, tests/feature-typescript-versions.test.js
Currently the `toAcceptProps()` matcher does not work on TypeScript 4.5 and below. Here is the fix.
=> fix: support `toAcceptProps()` on TypeScript 4.5 and below

source/output/CodeSpanText.tsx, source/output/diagnosticText.tsx
Warnings should look less alarming. Better to mark locations in yellow.
=> fix(output): mark warning locations in yellow

source/store/Fetcher.ts, source/store/ManifestWorker.ts, tests/validation-store.test.js, tests/validation-update.test.js
When requested, fetch must always suppress errors.
=> fix(store): if requested, always suppress errors when fetching manifest

source/store/ManifestWorker.ts, source/store/StoreService.ts, source/store/types.ts, tests/config-prune.test.js, tests/config-update.test.js, tests/feature-store.test.js, tests/validation-store.test.js, tests/validation-update.test.js
Since `npmRegistry` can be specified (#266), it is important to make sure that store manifest was created using the specified registry. Because packages must be fetched from the same registry.
This change is especially important for is split from #269.
=> fix(store): make sure the same `npmRegistry` is used to fetch metadata and packages

source/events/types.ts, source/handlers/RunReporter.ts, source/handlers/SetupReporter.ts, source/output/__tests__/addsPackageText.test.js, source/output/addsPackageText.tsx, source/output/index.ts, source/store/PackageService.ts
Renaming the `store:adds` event to better reflect the intent.
=> refactor(events, handlers, output, store): rename the `store:adds` event

source/store/PackageService.ts, source/store/StoreService.ts, source/store/TarReader.ts, tests/validation-store.test.js
After this change, the `typescript` packages will be extracted to a temporary directory and renamed afterwards.
=> feat(store): write `typescript` packages atomically

source/config/OptionValidator.ts, tests/validation-store.test.js, tests/validation-update.test.js
The `target` option validation should be less verbose (and somewhat less misleading), when manifest is not available.
=> fix(config): reduce verbosity of the `target` option validation

source/output/OutputService.ts, source/output/index.ts
Remove `OutputService` constructor options, because they didn’t proof to be useful.
=> refactor(output): remove `OutputService` constructor options

source/input/InputService.ts, source/input/index.ts
Remove `InputService` constructor options, because they were not anyhow useful.
=> refactor(input): remove `InputService` constructor options

source/cli/Cli.ts, source/config/CommandLineOptionsWorker.ts, source/config/ConfigFileOptionsWorker.ts, source/config/ConfigService.ts, source/config/EnvironmentService.ts, source/config/OptionValidator.ts, source/config/defaultOptions.ts, source/config/environmentOptions.ts, source/config/index.ts, source/config/types.ts, source/environment/index.ts, source/handlers/RunReporter.ts, source/output/OutputService.ts, source/store/StoreService.ts, source/tstyche.ts
Adding environment options to `ResolvedConfig`.
Note that `Environment` class is replaced with `environmentOptions`. But that will be rarely needed since the `ResolvedConfig` is passed around.
=> refactor: add environment options to `ResolvedConfig`

biome.json
Use configuration from `.editorconfig` to reduce duplication.
=> chore: use configuration from `.editorconfig`

source/path/Path.ts, tests/__snapshots__/validation-type-errors-describe-level-errors-stderr.snap.txt
Relative paths like `../../../build/index.d.ts` shouldn't be altered.
=> fix(path): fix relative path normalization logic

source/events/EventEmitter.ts, source/handlers/CancellationHandler.ts, source/handlers/ExitCodeHandler.ts, source/handlers/Reporter.ts, source/handlers/ResultHandler.ts, source/handlers/RunReporter.ts, source/handlers/SetupReporter.ts, source/handlers/SummaryReporter.ts, source/handlers/WatchReporter.ts, tests/integration-Runner.test.js
Renaming `on()` method of `EventHandler` interface. Less is less (;
=> refactor!: rename `on()` method of `EventHandler` interface

source/api/TSTyche.ts, source/cli/Cli.ts, source/output/OutputService.ts, source/reporters/BaseReporter.ts, source/reporters/ListReporter.ts, source/reporters/SetupReporter.ts, source/reporters/SummaryReporter.ts, source/reporters/WatchReporter.ts, source/runner/Runner.ts, tests/integration-Runner.test.js
Making the `OutputService` class not instantiable. This simplifies programmatic usage.
=> refactor!: make the `OutputService` class not instantiable

source/cli/Cli.ts, source/config/Config.ts, source/config/ConfigService.ts, source/config/index.ts, tests/integration-Runner.test.js
This PR reshapes all public methods of the `Config` class and makes it not instantiable. One more change to simplify programmatic usage.
=> refactor!: make the `Config` class not instantiable

scripts/generate-schema.js, scripts/generate-types.js, source/cli/Cli.ts, source/config/CommandLineParser.ts, source/config/ConfigFileParser.ts, source/config/Options.ts, source/config/index.ts, source/output/helpText.tsx
Renaming the `Options` class. Its previous name was rather verbose.
=> refactor!: rename the `Options` class

source/cli/Cli.ts, source/config/Config.ts, source/reporters/ListReporter.ts
Reverts #299.
Since the `ResolvedConfig` can be modified using plugins, it should not include any environment options. Because modifying those will have no effect. The environment variables should be the source of truth.
=> refactor: remove environment options to `ResolvedConfig`

source/cli/Cli.ts, source/hooks/HooksService.ts, source/hooks/types.ts, tests/__fixtures__/hooks-config/config-plugin-1.js, tests/__fixtures__/hooks-config/config-plugin-2.js, tests/__fixtures__/hooks-config/config-plugin-3.js, tests/__fixtures__/hooks-select/select-plugin-1.js, tests/__fixtures__/hooks-select/select-plugin-2.js, tests/__fixtures__/hooks-select/select-plugin-3.js
Hooks must return full object or `null` / `undefined`.
=> fix(hooks): require to return full object

source/runner/TaskRunner.ts, tests/__snapshots__/validation-select-stderr.snap.txt, tests/__snapshots__/validation-select-stdout.snap.txt, tests/validation-select.test.js
Currently a plugin could provide a path to not existing test file. And it will be marked as passed. That’s not good.
Fixing that. The missing file must be marked as failed and a message must be printed.
=> fix: mark not existing test file as failed

source/task/Task.ts, tests/__fixtures__/hooks-select/select-plugin-2.js, tests/integration-Runner.test.js
Test file paths must be always resolved.
=> fix(runner): always resolve test file paths

examples/example-plugin.tst.js, source/cli/Cli.ts, source/plugins/PluginService.ts, source/plugins/types.ts, tests/__fixtures__/hooks-config/config-plugin-1.js, tests/__fixtures__/hooks-config/config-plugin-2.js, tests/__fixtures__/hooks-config/config-plugin-3.js, tests/__fixtures__/hooks-select/select-plugin-1.js, tests/__fixtures__/hooks-select/select-plugin-2.js, tests/__fixtures__/hooks-select/select-plugin-3.js, tests/__fixtures__/hooks-select/tsconfig.json, tests/validation-select.test.js
Sounds useful to pass `ResolvedConfig` as context to the `select` hook.
=> feat: pass context to the `select` hook

source/plugins/PluginService.ts, source/plugins/index.ts, source/plugins/types.ts
Removing the `Hooks` interface. The `Plugin` interface must be used instead.
=> refactor: remove the `Hooks` interface

examples/exact-optional-properties.tst.ts, source/expect/MatchWorker.ts, tests/__fixtures__/api-toBe/__typetests__/toBe.tst.ts, tests/__fixtures__/api-toBe/tsconfig-exact.json, tests/__snapshots__/api-toBe-exact-stdout.snap.txt, tests/__snapshots__/api-toBe-stderr.snap.txt, tests/__snapshots__/api-toBe-stdout.snap.txt, tests/api-toBe.test.js
The following must pass when `"exactOptionalPropertyTypes": true` is set:
```ts
import { expect } from "tstyche";
expect<{ a?: number }>().type.not.toBe<{ a?: number | undefined }>();
expect<{ a?: number | undefined }>().type.not.toBe<{ a?: number }>();
```
---
Related: https://github.com/mmkal/expect-type/issues/128
=> fix(expect): take into account `exactOptionalPropertyTypes` option when comparing types

source/expect/ToRaiseError.ts, source/types.ts, tests/__fixtures__/api-toRaiseError/__typetests__/toRaiseError-regex.tst.ts, tests/__snapshots__/api-toRaiseError-regex-stderr.snap.txt, tests/__snapshots__/api-toRaiseError-regex-stdout.snap.txt, tests/__snapshots__/api-toRaiseError-stdout.snap.txt, tests/__snapshots__/validation-toRaiseError-stderr.snap.txt, tests/api-toRaiseError.test.js
As it was requested [on Discord](https://discord.com/channels/1205835073350406145/1205835074030018643/1301478794867249182).
The `.toRaiseError()` matcher could also take regular expressions. For instance, this can be used to match `/^The exact error message.$/`.
@SerkanSipahi Thanks for the idea!
=> feat: allow `.toRaiseError()` to take regular expressions

models/CommandLineOptions.ts, source/cli/Cli.ts, source/config/Options.ts, tests/__snapshots__/config-help-stdout.snap.txt, tests/config-list.test.js
Closes #363
Add the `--list` command line option. It prints out supported TypeScript tags and versions.
=> feat: add the `--list` command line option

models/CommandLineOptions.ts, source/cli/Cli.ts, source/config/Options.ts, source/store/Store.ts, tests/__snapshots__/config-help-stdout.snap.txt, tests/config-list.test.js
This PR makes the `--list` command line option more useful. It will print tag resolutions and supported versions. To have more details is always good idea.
=> refactor: make the `--list` command line option more useful

source/store/Store.ts, source/version/Version.ts, source/version/__tests__/Version.test.js
Deprecate the `Version.isVersionTag()` method. Name of this method is misleading and it is hardly needed.
=> refactor: deprecate the `Version.isVersionTag()` method

source/config/Config.ts, source/config/Options.ts, source/config/Target.ts, source/store/ManifestService.ts, tests/config-target.test.js, tests/validation-target.test.js
Closes #380
Currently `target` ranges only allow specifying supported minor versions. The following does not work: `--target '>=5.2 <5.8'`. But it should be allowed.
=> fix: allow specifying unsupported versions in `target` ranges

source/project/ProjectService.ts, source/reporters/ListReporter.ts
Seems better to emit the `project:uses` event once for each project.
=> fix: emit the `project:uses` event only once for each project

source/project/ProjectService.ts
To maximise performance, compiler options must be altered only when needed.
=> perf: alter compiler options only when needed

source/diagnostic/Diagnostic.ts, source/expect/ToRaiseError.ts, source/output/diagnosticText.tsx, source/project/ProjectService.ts, source/runner/TaskRunner.ts, source/runner/TestTreeWalker.ts, tests/__fixtures__/validation-type-errors/__typetests__/top-level.tst.ts, tests/__snapshots__/config-checkSourceFiles-enabled-stderr.snap.txt, tests/__snapshots__/validation-type-errors-top-level-errors-stderr.snap.txt
Error codes belong at the end of the first line of diagnostics. Therefor they must be print like this:
=> fix: print error codes at the end of the first line of diagnostics

source/expect/MatchWorker.ts, tests/__fixtures__/api-toBe/__typetests__/toBe.tst.ts, tests/__snapshots__/api-toBe-exact-stdout.snap.txt, tests/__snapshots__/api-toBe-stderr.snap.txt, tests/__snapshots__/api-toBe-stdout.snap.txt
Similar to what was mentioned in https://github.com/tsdjs/tsd/issues/223
An intersection like `{ a: string } & { a: string }` can be treated as identical to `{ a: string }`.
Or a union like `{ a: string } | { a: string }` can be treated as identical to `{ a: string }`.
EDIT: It would be nice to treat nested properties similarly as well. Leaving that for the bright future (;
=> fix: treat intersections or unions of identical types as identical to its constituent type

source/expect/MatchWorker.ts, tests/__fixtures__/api-toBe/__typetests__/toBe.tst.ts, tests/__snapshots__/api-toBe-exact-stdout.snap.txt, tests/__snapshots__/api-toBe-stderr.snap.txt, tests/__snapshots__/api-toBe-stdout.snap.txt
Following up #392 and #393.
Complex unions and intersections like `(({ a: string } & { a: string }) | { a: string }) & { a: string }` can be simplify to `{ a: string }`  for identicality checks.
=> fix: simplify complex unions and intersections for identicality checks

source/output/CodeFrameText.tsx, source/output/diagnosticText.tsx, source/output/index.ts, source/output/types.ts, tests/__snapshots__/feature-watch-config-file-has-an-error-stderr.snap.txt, tests/__snapshots__/validation-configFile-handles-crlf.snap.txt, tests/__snapshots__/validation-configFile-syntax-errors-root-brace.snap.txt, tests/__snapshots__/validation-configFile-syntax-errors-unquoted-values.snap.txt, tests/__snapshots__/validation-configFile-unknown-options.snap.txt, tests/__snapshots__/validation-expect-handles-nested-stderr.snap.txt, tests/__snapshots__/validation-failFast-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-it-handles-nested-stderr.snap.txt, tests/__snapshots__/validation-plugins-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-reporters-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-rootPath-path-does-not-exist.snap.txt, tests/__snapshots__/validation-rootPath-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-target-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-test-handles-nested-stderr.snap.txt
Adding `linesAbove` and `linesBelow` configuration options for code frame output. This makes usage of `diagnosticText()` component more flexible for integrations (e.g. custom reporters).
=> feat: make code frame output configurable

source/output/CodeFrameText.tsx, source/output/types.ts
Following up #407
Also adding `showBreadcrumbs` configuration options for code frame output.
=> feat: make code frame output even more configurable

source/version/Version.ts
Removing the deprecated `Version.isVersionTag()` method.
=> refactor!: remove `Version.isVersionTag()` method

models/CommandLineOptions.ts, models/__typetests__/CommandLineOptions.tst.ts, source/cli/Cli.ts, source/config/Options.ts, source/store/PackageService.ts, source/store/Store.ts, source/store/StoreDiagnosticText.ts, tests/__snapshots__/config-help-stdout.snap.txt, tests/config-fetch.test.js, tests/config-storePath.test.js, tests/config-typescriptModule.test.js, tests/feature-typescript-versions.test.js, tests/validation-store.test.js
Closes #374
Renaming the `--fetch` command line option.
=> refactor!: rename the `--fetch` command line option

.github/workflows/checks.yml, DEVELOPMENT.md, package.json, tests/feature-watch.test.js
Dropping support for Node.js 18. (The plan is to release TSTyche 4 after Node.js 18 will be end-of-life.)
=> chore!: drop support for Node.js 18

source/expect/ExpectService.ts
Marking `resolvedConfig` as required argument of `ExpectService` constructor.
=> refactor!: require passing `resolvedConfig` to `ExpectService` constructor

cspell.config.json, source/project/ProjectService.ts, tests/project-tsconfig.test.js
Closes #381
Making default compiler options more strict:
```json
{
"allowImportingTsExtensions": true,
"allowJs": true,
"checkJs": true,
"exactOptionalPropertyTypes": true,
"jsx": "preserve",
"module": "nodenext",
"moduleResolution": "nodenext",
"noUncheckedIndexedAccess": true,
"resolveJsonModule": true,
"strict": true,
"target": "esnext",
"verbatimModuleSyntax": true
}
```
=> feat!: make default compiler options strict

source/diagnostic/Diagnostic.ts, source/expect/ToRaiseError.ts
Whitespace should be ignored when comparing TypeScript’s diagnostic messages.
=> fix: exclude whitespace when comparing diagnostic messages

source/project/ProjectService.ts, source/runner/Runner.ts, source/runner/TaskRunner.ts, source/runner/TestTreeWalker.ts
Cleaning up. The `compiler` argument must be always the first one in constructors.
=> refactor!: always take `compiler` as the first constructor argument

source/collect/AbilityLayer.ts, tests/__snapshots__/api-toBeApplicable-stderr.snap.txt
Diagnostics of the ability layer must not be reversed. Otherwise they are reported in a wrong order (not the same as in TypeScript).
=> fix: do not reverse diagnostics of the ability layer

source/expect/ToBeCallableWith.ts, tests/__snapshots__/validation-toBeCallableWith-stderr.snap.txt
Relaxing validation of the target of `.toBeCallableWith()` matcher. It seems that current validation logic is too strict in the real world usage.
=> fix: relax validation of the target of `.toBeCallableWith()` matcher

source/expect/MatchWorker.ts, source/expect/ToBeCallableWith.ts, tests/__fixtures__/validation-toBeCallableWith/__typetests__/toBeCallableWith.tst.ts, tests/__snapshots__/validation-toBeCallableWith-stderr.snap.txt, tests/__snapshots__/validation-toBeCallableWith-stdout.snap.txt
Adding validation of the source node passed to the `.toBeCallableWith()` matcher.
=> feat: add validation of the source node passed to `.toBeCallableWith()`

source/collect/AbilityLayer.ts, source/expect/ToBeCallableWith.ts, tests/__fixtures__/validation-toBeCallableWith/__typetests__/toBeCallableWith.tst.ts, tests/__snapshots__/validation-toBeCallableWith-stderr.snap.txt, tests/__snapshots__/validation-toBeCallableWith-stdout.snap.txt
This change allows using `.toBeCallableWith()` with: arrow functions, function declarations and function expressions.
=> feat: allow using `.toBeCallableWith()` with more callable expressions

source/collect/AbilityLayer.ts, tests/__snapshots__/api-toBeCallableWith-stdout-missing-semicolons.snap.txt, tests/__snapshots__/api-toBeConstructableWith-stdout-missing-semicolons.snap.txt, tests/api-toBeCallableWith.test.js, tests/api-toBeConstructableWith.test.js
The ability layer must handle missing semicolons by inserting them.
=> fix: insert missing semicolons in the ability layer text

source/expect/ToBeCallableWith.ts, source/expect/ToBeConstructableWith.ts, tests/__fixtures__/validation-toBeCallableWith/__typetests__/toBeCallableWith.tst.ts, tests/__fixtures__/validation-toBeConstructableWith/__typetests__/toBeConstructableWith.tst.ts, tests/__snapshots__/validation-toBeCallableWith-stderr.snap.txt, tests/__snapshots__/validation-toBeCallableWith-stdout.snap.txt, tests/__snapshots__/validation-toBeConstructableWith-stderr.snap.txt, tests/__snapshots__/validation-toBeConstructableWith-stdout.snap.txt
Property access expressions must be accepted by the callability matchers.
=> fix: allow passing property access expressions to the callability matchers

source/collect/CollectDiagnosticText.ts, source/collect/CollectService.ts, source/events/types.ts, source/handlers/ResultHandler.ts, source/reporters/ListReporter.ts, source/runner/TaskRunner.ts, source/token/CancellationReason.enum.ts, tests/__fixtures__/validation-when/__typetests__/handles-nested.tst.ts, tests/__snapshots__/validation-when-handles-nested-stderr.snap.txt, tests/__snapshots__/validation-when-handles-nested-stdout.snap.txt, tests/api-when.test.js, tests/validation-when.test.js
This is adding the missing nesting validation of the `when()` utility.
=> feat: add `when()` nesting validation

.github/workflows/checks.yml, benchmarks/tstyche.bench.sh, examples/template.tst.ts, package.json, source/runner/Runner.ts, source/runner/TaskRunner.ts, tests/__fixtures__/api-template/__typetests__/template.tst.ts, tests/__fixtures__/api-template/tsconfig.json, tests/__snapshots__/api-template-stderr.snap.txt, tests/__snapshots__/api-template-stdout.snap.txt, tests/api-template.test.js, yarn.lock
Closes #465
This adds template test file support.
To mark a test file as a temple, a user must include `// @tstyche-template` as the first line of a test file.
When the `// @tstyche-template` directive is detected, the default export of a file is treated as a type test file.
For example, the following:
```ts
// @tstyche-template
let testText = `
import { expect, test } from "tstyche";
`;
for (const target of ["string", "number"]) {
testText += `test("is ${target} a string?", () => {
expect<string>().type.toBe<${target}>();
});
`;
}
export default testText;
```
is treated as:
```ts
import { expect, test } from "tstyche";
test("is string a string?", () => {
expect<string>().type.toBe<string>();
});
test("is number a string?", () => {
expect<string>().type.toBe<number>();
});
```
=> feat: add template test file support

source/project/ProjectService.ts, tests/__snapshots__/config-tsconfig-not-include-stdout.snap.txt, tests/config-tsconfig.test.js
Fixes #472
When the `tsconfig` option is used to provide path to TSConfig file explicitly, the default compiler option must be used when file is not included.
=> fix: always use default compiler options when file is not included

source/project/ProjectService.ts
The ability layer or template test file feature are both opening the same file twice, but the program has changed. No need to typecheck source files again, because that was done already.
=> fix: do not typecheck already seen test files

source/collect/CollectService.ts, source/collect/IdentifierLookup.ts, source/collect/TestTreeNode.ts, source/runner/TaskRunner.ts, source/runner/TestTreeWalker.ts, source/token/CancellationReason.enum.ts, tests/__fixtures__/validation-it/__typetests__/handles-nested.tst.ts, tests/__fixtures__/validation-test/__typetests__/handles-nested.tst.ts, tests/__fixtures__/validation-when/__typetests__/handles-nested.tst.ts, tests/__snapshots__/validation-describe-handles-expect-stderr.snap.txt, tests/__snapshots__/validation-describe-handles-expect-stdout.snap.txt, tests/__snapshots__/validation-expect-handles-nested-stderr.snap.txt, tests/__snapshots__/validation-expect-handles-nested-stdout.snap.txt, tests/__snapshots__/validation-it-handles-nested-stderr.snap.txt, tests/__snapshots__/validation-it-handles-nested-stdout.snap.txt, tests/__snapshots__/validation-test-handles-nested-stderr.snap.txt, tests/__snapshots__/validation-test-handles-nested-stdout.snap.txt, tests/__snapshots__/validation-when-handles-nested-stderr.snap.txt, tests/__snapshots__/validation-when-handles-nested-stdout.snap.txt
Moving test tree validation logic to the collect service.
This is breaking change, because the invalid nodes are not included in the tree anymore. Errors are emitted as diagnostics, test file fails, but all healthy nodes are analyzed and results are reported.
=> refactor!: move test tree validation logic

source/collect/AbilityLayer.ts, source/collect/helpers.ts
Prepend comma on before expression statements in the ability layer.
I found a case where `expect()` can be used as a body of an arrow function: `const x = () => expect...`. Probably there are other cases.
=> fix: prepend comma on before expression statements in the ability layer

source/config/Directive.ts, tests/__snapshots__/directive-if-target-with-note-stdout.snap.txt, tests/directive-if-target.test.js, tests/directive-template.test.js
The directives are comments. Adding a note with explanation is useful. The note text must be separated by two or more dashes:
```ts
// @tstyche template -- For documentation, see: https://tstyche.org/guide/template-test-files.
```
```ts
// @tstyche if { target: [">=5.7"] } -- For lower versions, the inferred type is 'unknown'.
```
=> feat: allow adding notes to the directive comments

examples/conditional.tst.ts, source/collect/AssertionNode.ts, tests/__fixtures__/api-expect/__typetests__/expect-skip.tst.ts, tests/__snapshots__/api-expect-skip-stdout.snap.txt
It should be allowed to skip `target` type errors as well.
=> fix: allow skipping `target` type errors

source/collect/AbilityLayer.ts, source/collect/types.ts, source/config/Directive.ts, source/config/index.ts, source/diagnostic/Diagnostic.ts, source/expect/AbilityMatcherBase.ts, source/expect/ToBeCallableWith.ts, source/expect/ToBeConstructableWith.ts, source/output/CodeFrameText.tsx, tests/__snapshots__/api-toBeCallableWith-generic-functions-stderr.snap.txt, tests/__snapshots__/api-toBeCallableWith-overload-signatures-stderr.snap.txt, tests/__snapshots__/api-toBeCallableWith-parameter-arity-stderr.snap.txt, tests/__snapshots__/api-toBeCallableWith-rest-parameters-stderr.snap.txt, tests/__snapshots__/api-toBeCallableWith-trailing-comma-stderr.snap.txt, tests/__snapshots__/api-toBeCallableWith-ts-expect-error-stderr.snap.txt, tests/__snapshots__/api-toBeCallableWith-ts-expect-error-stdout.snap.txt, tests/__snapshots__/api-toBeConstructableWith-generic-classes-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-overload-signatures-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-parameter-arity-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-rest-parameters-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-trailing-comma-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-ts-expect-error-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-ts-expect-error-stdout.snap.txt, tests/__snapshots__/api-when-stderr.snap.txt, tests/__snapshots__/api-when-trailing-comma-stderr.snap.txt, tests/__snapshots__/validation-expect-handles-nested-stderr.snap.txt, tests/__snapshots__/validation-when-action-not-supported-stderr.snap.txt, tests/__snapshots__/validation-when-action-not-supported-stdout.snap.txt, tests/api-toBeCallableWith.test.js, tests/api-toBeConstructableWith.test.js
The ability layer should always erase the `// @ts-expect-error` directives, because it depends on errors being visible.
=> fix(ability): always erase the `// @ts-expect-error` directives

source/collect/AbilityLayer.ts, source/collect/types.ts, source/diagnostic/Diagnostic.ts, source/suppressed/SuppressedService.ts, tests/__fixtures__/validation-expect/__typetests__/matcher-not-supported.tst.ts, tests/__fixtures__/validation-toHaveProperty/__typetests__/toHaveProperty.tst.ts, tests/__fixtures__/validation-toRaiseError/__typetests__/toRaiseError.tst.ts, tests/__fixtures__/validation-when/__typetests__/action-not-supported.tst.ts, tests/__snapshots__/config-rejectAnyType-enabled-stderr.snap.txt, tests/__snapshots__/validation-expect-handles-not-supported-matcher-stderr.snap.txt, tests/__snapshots__/validation-toHaveProperty-stderr.snap.txt, tests/__snapshots__/validation-toRaiseError-stderr.snap.txt, tests/__snapshots__/validation-when-action-not-supported-stderr.snap.txt, tests/config-rejectAnyType.test.js
The ignored `// @ts-expect-error` directives must be filtered out later. Otherwise they are not erased.
=> refactor: move suppressed error ignore logic to service

schemas/__tests__/__fixtures__/invalid-fixtureFileMatch-1.json, schemas/__tests__/__fixtures__/invalid-fixtureFileMatch-2.json, schemas/__tests__/__fixtures__/invalid-fixtureFileMatch-3.json, schemas/__tests__/__fixtures__/valid-all-options.json, schemas/__tests__/__fixtures__/valid-fixtureFileMatch.json, schemas/__tests__/config-schema.test.js, schemas/config.json, source/config/ConfigDiagnosticText.ts, source/config/Options.ts, source/config/defaultOptions.ts, source/config/types.ts, source/project/ProjectService.ts, source/select/Select.ts, tests/__snapshots__/config-fixtureFileMatch-default-patterns-typetests-stderr.snap.txt, tests/__snapshots__/config-fixtureFileMatch-default-patterns-typetests-stdout.snap.txt, tests/__snapshots__/config-fixtureFileMatch-specified-patterns-empty-list-stderr.snap.txt, tests/__snapshots__/config-fixtureFileMatch-specified-patterns-empty-list-stdout.snap.txt, tests/__snapshots__/config-fixtureFileMatch-specified-patterns-stderr.snap.txt, tests/__snapshots__/config-fixtureFileMatch-specified-patterns-stdout.snap.txt, tests/__snapshots__/config-fixtureFileMatch-when-checkSourceFiles-disabled-stderr.snap.txt, tests/__snapshots__/config-fixtureFileMatch-when-checkSourceFiles-disabled-stdout.snap.txt, tests/__snapshots__/validation-fixtureFileMatch-cannot-start-with-dot-dot-slash.snap.txt, tests/__snapshots__/validation-fixtureFileMatch-cannot-start-with-slash.snap.txt, tests/__snapshots__/validation-fixtureFileMatch-wrong-list-item-type-stderr.snap.txt, tests/__snapshots__/validation-fixtureFileMatch-wrong-option-value-type-stderr.snap.txt, tests/__snapshots__/validation-testFileMatch-cannot-start-with-dot-dot-slash.snap.txt, tests/config-fixtureFileMatch.test.js, tests/validation-fixtureFileMatch.test.js, typetests/ConfigFileOptions.tst.ts
Closes #532
Add the `fixtureFileMatch` configuration option. It will allow checking fixture files without `checkSourceFiles` enabled.
=> feat: add the `fixtureFileMatch` configuration option

.github/workflows/checks.yml, .mise/config.toml
Let’s use Yarn from npm instead of the `mise-yarn` plugin. (If Windows allows.)
=> chore(ci): use Yarn from npm

.github/workflows/checks.yml, package.json
This drops support for older Node.js 20 versions (to stay in parity with [`create-tstyche`](https://github.com/tstyche/create-tstyche)).
=> chore!: drop support for older Node.js 20 versions

source/collect/AbilityLayer.ts, source/config/Directive.ts, tests/__snapshots__/config-checkSuppressedErrors-enabled-stderr.snap.txt, tests/config-checkSuppressedErrors.test.js
Leading tabs must be taken into account when collecting directives.
=> fix: handle leading tabs when collecting directives

source/project/ProjectService.ts
Removing `allowJs` and `checkJs` from default compiler options. Seems like they are not really useful.
=> refactor!: remove `allowJs` and `checkJs` from default compiler options

source/output/summaryText.tsx, source/result/DescribeResult.ts, source/result/ExpectResult.ts, source/result/FileResult.ts, source/result/Result.ts, source/result/ResultCounts.ts, source/result/ResultTiming.ts, source/result/TargetResult.ts, source/result/TestResult.ts, source/result/helpers.ts, source/result/index.ts, source/result/types.ts, tests/integration-Runner.test.js
Exporting `ResultCounts` and `ResultTiming` as types only.
Also `AssertionCounts`, `TestCounts`, `FileCounts`, `TargetCounts` are added to make typings more precise.
=> refactor!: export `ResultCounts` and `ResultTiming` as types only

package.json, scripts/rollup.ts
Close #585
This provides declaration file with `DecoratorContext` type omitted for TypeScript `4.x`.
=> fix: provide correct declaration file for TypeScript `4.x`

source/collect/CollectService.ts, source/collect/IdentifierLookup.ts, source/collect/TestTreeNodeBrand.enum.ts, source/runner/FixmeService.ts, source/runner/TestTreeWalker.ts, source/types.ts, tests/__snapshots__/directive-fixme-only-stderr.snap.txt
Adding the `TestTreeNodeBrand.It` member. After this change it becomes straight forward to get the name of a test node.
=> feat: add `TestTreeNodeBrand.It` member

source/expect/MatchWorker.ts, source/expect/ToHaveProperty.ts, source/expect/types.ts, source/layers/AbilityLayer.ts, source/store/Store.ts, tests/__fixtures__/api-toHaveProperty/__typetests__/toHaveProperty.tst.ts, tests/__snapshots__/api-toHaveProperty-stderr.snap.txt, tests/__snapshots__/api-toHaveProperty-stdout.snap.txt
This change implements `.toHaveProperty()` matcher using the ability layer.
=> refactor!: implement `.toHaveProperty()` matcher using the ability layer

examples/Newable.tst.ts, source/expect/ToBeConstructableWith.ts, source/layers/AbilityLayer.ts, tests/__fixtures__/api-toBeConstructableWith/__typetests__/generic-classes.tst.ts, tests/__fixtures__/api-toBeConstructableWith/__typetests__/overload-signatures.tst.ts, tests/__fixtures__/api-toBeConstructableWith/__typetests__/parameter-arity.tst.ts, tests/__fixtures__/api-toBeConstructableWith/__typetests__/rest-parameters.tst.ts, tests/__fixtures__/validation-toBeConstructableWith/__typetests__/toBeConstructableWith.tst.ts, tests/__snapshots__/api-toBeConstructableWith-generic-classes-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-generic-classes-stdout.snap.txt, tests/__snapshots__/api-toBeConstructableWith-overload-signatures-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-overload-signatures-stdout.snap.txt, tests/__snapshots__/api-toBeConstructableWith-parameter-arity-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-parameter-arity-stdout.snap.txt, tests/__snapshots__/api-toBeConstructableWith-rest-parameters-stderr.snap.txt, tests/__snapshots__/api-toBeConstructableWith-rest-parameters-stdout.snap.txt, tests/__snapshots__/validation-toBeConstructableWith-stderr.snap.txt, tests/__snapshots__/validation-toBeConstructableWith-stdout.snap.txt
Partly #592
Currently `.toBeConstructableWith()` can only test inferred types of expressions. This change enables testing of provided types as well:
```ts
import { expect, test } from "tstyche";
type Newable<T extends abstract new (...args: any) => any> = {
new (...args: ConstructorParameters<T>): InstanceType<T>;
};
declare class Person {
constructor(name: string, age: number);
}
test("PersonConstructor", () => {
expect<Newable<typeof Person>>().type.toBeConstructableWith("Alice", 30);
expect<Newable<typeof Person>>().type.not.toBeConstructableWith("Alice");
});
```
=> feat: enable testing of provided types with `.toBeConstructableWith()`

package.json, scripts/rollup.ts, source/project/ProjectService.ts, source/store/ManifestService.ts, source/store/PackageService.ts, tests/feature-typescript-versions.test.js, yarn.lock
This PR drops support for TypeScript `4.x`.
=> refactor!: drop support for TypeScript `4.x`
